apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server-deployment
  # annotations:
    # kubernetes.io/change-cause: version 1.10.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-deployment
  template:
    metadata:
      labels:
        app: server-deployment
    spec:
      containers:
      - name: server-deployment
        image: tndyd5390/nonstop-server:0.1
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
      terminationGracePeriodSeconds: 10
